#!/bin/bash
echo diff -b OUT.TEST/out1.txt OUT.RT/out1.txt
diff -b OUT.TEST/out1.txt OUT.RT/out1.txt

echo diff -b OUT.TEST/out2.txt OUT.RT/out2.txt
diff -b OUT.TEST/out2.txt OUT.RT/out2.txt

echo cmp -b OUT.TEST/infections1.txt OUT.RT/infections1.txt
cmp -b OUT.TEST/infections1.txt OUT.RT/infections1.txt

echo cmp -b OUT.TEST/infections2.txt OUT.RT/infections2.txt
cmp -b OUT.TEST/infections2.txt OUT.RT/infections2.txt

