#!/usr/bin/perl
use warnings;
use strict;

open IN,"states.txt";
while (my $line = <IN>) {
  chomp $line;
  my ($fips,$abbr,$name,$ymin,$ymax,$xmin,$xmax)=split '\t',$line;
  system "make_state $fips $ymin $ymax $xmin $xmax";
}
