##################### FRED Makefile for tests ###########################

all:
	

tests:
	fred_make_rt antivirals
	fred_make_rt
	#fred_make_rt evolution
	fred_make_rt multi_dose
	fred_make_rt vaccine
	fred_make_rt vaccine_ACIP

clean:
	rm -rf */OUT.TEST

