##################### FRED Makefile for tests ###########################

all:
	

tests:
	make_rt antivirals
	make_rt
	#make_rt evolution
	make_rt multi_dose
	make_rt vaccine
	make_rt vaccine_ACIP

clean:
	rm -rf */OUT.TEST

