##################### FRED Makefile for tests ###########################

all:
	

tests:
	fred_make_rt
	fred_make_rt vaccine
	fred_make_rt antivirals
	rm -rf */OUT.TEST */compare.test */OUT.RT/LOG*

clean:
	rm -rf */OUT.TEST

