#!/usr/bin/perl
use strict;
use warnings;

my ($notes,$years,$ages,$births,$fpop,$rate) = ();
open OUT,">birth_rates.txt";
open IN,"US_birth_rates_2010.txt";
<IN>;
for my $group (1..6) {
  my $line = <IN>;
  chomp $line;
  ($notes,$years,$ages,$births,$fpop,$rate) = split "\t", $line;
  $rate /= 1000.0;
  my ($low,$hi) = $ages =~ /(\d+)\-(\d+)/;
  for my $age ($low..$hi) {
    printf OUT "$age\t%e\n", $rate;
  }   
}
for my $age (45..49) {
  printf OUT "$age\t%e\n", 0.1*$rate;
}   
close IN;
close OUT;


