#!/usr/bin/perl
use strict;
use warnings;

open OUT,">mortality_rates.txt";

my ($notes,$years,$age,$gender,$sex,$deaths,$pop,$frate,$mrate) = ();
open IN,"US_mortality_rates_2010.txt";
<IN>;
for my $age (0..84) {
  my $line = <IN>;
  chomp $line;
  ($notes,$years,$age,$gender,$sex,$deaths,$pop,$frate) = split "\t", $line;
  $age =~ s/\"//g;
  $sex =~ s/\"//g;
  $frate /= 100000.0;
  $line = <IN>;
  chomp $line;
  ($notes,$years,$age,$gender,$sex,$deaths,$pop,$mrate) = split "\t", $line;
  $age =~ s/\"//g;
  $sex =~ s/\"//g;
  $mrate /= 100000.0;
  printf OUT "$age\t%e\t%e\n", $frate, $mrate;
}
close IN;
for my $age (85..120) {
  $frate = 1.1 * $frate;
  $mrate = 1.1 * $mrate;
  $frate = 1.0 if $frate > 1.0;
  $mrate = 1.0 if $mrate > 1.0;
  printf OUT "$age\t%e\t%e\n", $frate, $mrate;
}
close OUT;


