#!/usr/bin/perl
use strict;
use warnings;

my %statefips = ();
open IN,"states.txt";
open STATES, "../US_states.txt";
while (my $line = <STATES>) {
  chomp $line;
  my ($f,$a,$name) = split '\t', $line;
  $statefips{$name} = $f;
}
close STATES;
for my $st (keys %statefips) {
 # print "$statefips{$st} $st\n";
}

# ignore header;
my $line = <IN>;
while (not eof IN) {
  $line = <IN> while (not eof IN and $line !~ /state name/);
  if ($line =~ /state name/) {
    chomp $line;
    # print "$line\n";
    my ($name) = $line =~ /state name =(.*) col/;
    $name =~ s/\"//g;
    # print "|$name|\n";
    my $fips = $statefips{$name};
    print "$fips $name\n";
    open OUT,">$fips.txt";
    my $first_lat = 0;
    my $first_lon = 0;
    my $first = 1;
    while ($line = <IN>) {
      last if $line =~ "/state";
      my ($lat,$lon) = $line =~ /lat=(.*) lng=(.*)\//;
      $lat =~ s/\"//g;
      $lon =~ s/\"//g;
      print OUT "$lat $lon\n";
      if ($first) {
	$first_lat = $lat;
	$first_lon = $lon;
	$first = 0;
      }
    }
    print OUT "$first_lat $first_lon\n";
    close OUT;
  }
  $line = "";
}

