#!/usr/bin/perl
use strict;
use warnings;

my $usage = "usage: $0 infile outfile";
my ($infile,$outfile) = @ARGV;
$infile = "US_birth_rates_2010.txt"  if not $infile;
$outfile = "birth_rates.txt"  if not $outfile;
die $usage if not -e $infile;

my ($notes,$years,$ages,$births,$fpop,$rate) = ();
open IN,$infile or die "FILE $infile not found\n$usage\n";
open OUT,">$outfile" or die "$usage\n";
<IN>;
for my $group (1..6) {
  my $line = <IN>;
  chomp $line;
  ($notes,$years,$ages,$births,$fpop,$rate) = split "\t", $line;
  $rate /= 1000.0;
  my ($low,$hi) = $ages =~ /(\d+)\-(\d+)/;
  for my $age ($low..$hi) {
    printf OUT "$age\t%e\n", $rate;
  }   
}
for my $age (45..49) {
  printf OUT "$age\t%e\n", 0.1*$rate;
}   
close IN;
close OUT;


