#!/usr/bin/perl
use strict;
use warnings;

my ($notes,$state,$fips,$years,$ages,$rate) = ();
open OUT,">birth_rates.txt";
open IN,"US_birth_rates_by_state_2010.txt";
<IN>;
for my $st (0..50) {
  for my $group (1..6) {
    my $line = <IN>;
    chomp $line;
    ($notes,$state,$fips,$years,$ages,$rate) = split "\t", $line;
    $rate /= 1000.0;
    $fips =~ s/\"//g;
    my ($low,$hi) = $ages =~ /(\d+)\-(\d+)/;
    for my $age ($low..$hi) {
      printf OUT "$fips\t$age\t%e\n", $rate;
    }   
  }
  for my $age (45..49) {
    printf OUT "$fips\t$age\t%e\n", 0.1*$rate;
  }   
}
close IN;
close OUT;


