#!/usr/bin/perl
use strict;
use warnings;

my $fipslist = `ls ../SHAPES/*.txt`;
$fipslist =~ s/\.\.\/SHAPES\///g;
$fipslist =~ s/\.txt\n/ /g;
# print "$fipslist\n"; exit;
my @allfips = split " ", $fipslist;
for my $fips (@allfips) {
  system "make_fips $fips";
}

