#!/bin/csh
#
# See README for explanations and hints
#
# CONFIGURATION
set cores = 64
set runs = 5
set batches = 64
set timer = 2:00:00
set jobname = fred_schools.$cores
set email = gref@pitt.edu

# CLEANUP
rm -rf PARAMDIR TASKDIR BATCHDIR OUT 

# MAKE TASKS FILE
fred_experiment_space -n $runs -m 1 -c 1 -d 0 -f config -r RESULTS.$cores

# MAKE BATCHESFILE and QSUB FILE
fred_make_qsub --task tasks.school_closure -n $batches -c $cores -j $jobname -t $timer

# SUBMIT TO QUEUE
# qsub -m abe -M $email $jobname > qsub.out
