#!/usr/bin/perl
use warnings;
use strict;

my ($fips,$ymin,$ymax,$xmin,$xmax) = @ARGV;
$ymin = 0 if not $ymin;
$ymax = 0 if not $ymax;
$xmin = 0 if not $xmin;
$xmax = 0 if not $xmax;
my $adjust = 0;
$adjust = 1 if ($ymin eq 0 and $ymax eq 0 and $xmin eq 0 and $xmax eq 0);
system "gnuplot -e 'force_ymin=$ymin; force_ymax=$ymax; force_xmin=$xmin; force_xmax=$xmax; adjust=$adjust' make_map";
system "mv map.png $fips.png";
system "mv RANGES.plt $fips.boundaries";
system "rm back* tmp* google* crop*";
