#!/usr/bin/perl
use warnings;
use strict;

open IN,"states.txt";
while (my $line = <IN>) {
  chomp $line;
  my ($fips,$abbr,$name,$ymin,$ymax,$xmin,$xmax)=split '\t',$line;
  system "echo $fips > FIPS";
  my $adjust = 0;
  $adjust = 1 if ($ymin eq 0 and $ymax eq 0 and $xmin eq 0 and $xmax eq 0);
  system "gnuplot -e 'force_ymin=$ymin; force_ymax=$ymax; force_xmin=$xmin; force_xmax=$xmax; adjust=$adjust' make_map";
  system "mv map.png $fips.png";
  system "mv RANGES.plt $fips.boundaries";
  system "rm back* tmp* google* crop*";
}
